### ISSUE TITLE
The search box on the documentation site throws 404

### ISSUE THREAD

**Issue by kkh451** [metaRange/metaRange#2]
The [documentation site](https://metarange.github.io/metaRange/index.html) has a search box (page top right). 

Entering search text and hitting return results in a  404 error:

```
404
There isn't a GitHub Pages site here.

If you're trying to publish one, [read the full documentation](https://help.github.com/pages/) to learn how to set up GitHub Pages for your repository, organization, or user account. 
```

**Comment by srfall** [comment]
thanks for the report. Should be fixed with https://github.com/metaRange/metaRange/commit/bb12cde9449efb9fc78cff797dffd59b99695611
